### ISSUE TITLE
typo on Third Addendum

### ISSUE THREAD

**Issue by tnvu** [sarabander/sicp#1]
s/Techical/Technical/

**Comment by guyueshui** [comment]
Sorry for bothering, i wonder if there is a typo at [section 1.2.2 footnote#34](https://sarabander.github.io/sicp/html/1_002e2.xhtml#DOCF34): s/memoization/memorization

**Comment by cdlm** [comment]
Memoization is the correct term in this context (granted, it's a neologism).

**Comment by guyueshui** [comment]
> Memoization is the correct term in this context (granted, it's a neologism).

Thank you, got it!
