### ISSUE TITLE
How can I read it online?

### ISSUE THREAD

**Issue by halida** [sarabander/sicp#10]
You should create a git page for this project.

**Comment by k4rtik** [comment]
Start from here: https://sarabander.github.io/sicp/html/

I understand it's not obvious how to access the book from the URL: https://sarabander.github.io/sicp/ You just had to click on the cover page. :smile:

**Comment by halida** [comment]
@k4rtik I think you should place this link in the readme. :)

**Comment by k4rtik** [comment]
@halida I am not the maintainer, just a fellow reader. Feel free to send a PR yourself.

**Comment by sarabander** [comment]
The link is in readme now.

**Comment by k4rtik** [comment]
:+1:
